### ISSUE TITLE
Cannot build when a Dockerfile is outside the build context

### ISSUE THREAD

**Issue by kerren** [kerren/dockem#1]
When running a build where the Dockerfile is outside the build context, I get the following error:

```
ERROR: An error ocurred when trying to build the image: Error response from daemon: forbidden path outside the build context: ../devops/production/website/Dockerfile ()
panic: Error response from daemon: forbidden path outside the build context: ../devops/production/website/Dockerfile ()
goroutine 1 [running]:
dockem/cmd.init.func1(0x973d60, {0x5586b8?, 0x4?, 0x55869c?})
	/home/***/src/dockem/cmd/build.go:63 +0x428
github.com/spf13/cobra.(*Command).execute(0x973d60, {0x40000b2f40, 0x4, 0x4})
	/home/***/.go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0x828
github.com/spf13/cobra.(*Command).ExecuteC(0x974040)
	/home/***/.go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:[11](https://github.com/entrostat/xxxxxxx#step:6:12)15 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	/home/***/.go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
dockem/cmd.Execute()
	/home/***/src/dockem/cmd/root.go:19 +0x24
main.main()
	/home/***/src/dockem/main.go:6 +0x1c
```

**Comment by kerren** [comment]
This has been resolved with PR #2
